# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NgoPdfParser
                                 A QGIS plugin
 This plugin parse pdf files with NGO data and create table with result
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-02-26
        copyright            : (C) 2024 by Bohdan2505
        email                : bogdan.zhuravel.00@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load NgoPdfParser class from file NgoPdfParser.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .UA_NGO_PDF_Parser import NgoPdfParser
    return NgoPdfParser(iface)
